voda-py/app/app/routes.py
from flask import Blueprint, render_template, send_from_directory, current_app
import os, time
from datetime import datetime

from .queries import query_battery, query_count, query_hladina, query_max_time
from .models import VodaFull, db

# Vytvoření blueprintu pro aplikaci
main_bp = Blueprint(
    'main_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


# Úvodní stránka obsahující pouze navigační menu a mapu
@main_bp.route('/', methods=['GET'])
def home():
 
    # Vrátí z databáze všechny hlásiče podle pohledu VodaFull
    hlasice = db.session.query(VodaFull).order_by(VodaFull.ORP.asc()).all()

    # Vygeneruje stránku podle přiloženého templatua pošle ji další argumenty
    return render_template(
        'home.html',
        hlasice=hlasice, # Stránce pošleme hlásiče z databáze
        curpage="home", # Označení nynější stránky pro zvýraznění v navbaru
        title="Portabo Voda",
        description="Voda hlásiče"
    )

# Funkce pro zobrazení všech aktivních hlásičů
@main_bp.route('/stanice', methods=['GET'])
def hlasice():
 # Slovník okresů
    okresy = {
        'Bílina':[],'Děčín':[],'Kadaň':[],'Chomutov':[],'Litomeřice':[],'Litvínov':[],'Lovosice':[],'Louny':[],
        'Most':[],'Podbořany':[],'Roudnice nad Labem':[],'Rumburk':[],'Teplice':[],'Ústí nad Labem':[],'Varnsdorf':[],'Žatec':[]
    }
    orp_to_okres = {
        'BI':'Bílina','DE':'Děčín','KA':'Kadaň','CH':'Chomutov','LI':'Litomeřice','LT':'Litvínov','LO':'Lovosice','LY':'Louny',
        'MO':'Most','PO':'Podbořany','RL':'Roudnice nad Labem','RU':'Rumburk','TE':'Teplice','UL':'Ústí nad Labem','VA':'Varnsdorf','ZA':'Žatec'
    }

    hlasice = db.session.query(VodaFull).order_by(VodaFull.ORP.asc()).all()
    pocetHlasicu = db.session.query(VodaFull).order_by(VodaFull.ORP.asc()).count()

    i = 0
    delitel = []
    for hlasic in hlasice:
        ORP = hlasic.ORP[0:2]
        okresy[orp_to_okres[ORP]].append(hlasic)
        if (i > pocetHlasicu/2 and delitel==[]):
            delitel.append(orp_to_okres[ORP])
        i += 1
        # print(okres)

    # print(okresy)

    print("Delitel: {}".format(delitel))

    # Vygeneruje stránku podle přiloženého templatua pošle ji další argumenty
    return render_template(
        'profilyHlasicu.html',
        curpage="profily", # Označení nynější stránky pro zvýraznění v navbaru
        pocetHlasicu=pocetHlasicu,
        hlasice=okresy,
        delitel=delitel,
        title="Portabo Voda Hlásiče",
        description="Seznam všech používaných hlásičů"
    )

# Funkce pro zobrazení jednoho určitého hlásice podle ORP
@main_bp.route('/stanice/<orp>', methods=['GET'])
def hlasic(orp):
    start = time.time()

    # Pokusí se vyhledat hlásič podle zadaného ORP, pokud neexistuje, tak vypíše chybovou hlášku.
    hlasic = db.session.query(VodaFull).get_or_404(orp, description="Hlásič {} neexistuje.".format(orp))
   
    # Najít historii hladiny za posledních 28 dnů
    graph = db.session.execute(query_hladina,{"now":datetime.now(),"inter":30,"orp":orp})
    graphCount = db.session.execute(query_count,{"now":datetime.now(),"inter":30,"orp":orp}).first()[0]
    # Najít historii hladiny za posledních 24 hodin
    graph24 = db.session.execute(query_hladina,{"now":datetime.now(),"inter":1,"orp":orp})
    graphCount24 = db.session.execute(query_count,{"now":datetime.now(),"inter":1,"orp":orp}).first()[0]
    # Najít historii baterky za poslední tři měsíce
    graphbattery = db.session.execute(query_battery,{"now":datetime.now(),"inter":90,"orp":orp})
    graphBatteryCount = db.session.execute(query_count,{"now":datetime.now(),"inter":90,"orp":orp}).first()[0]
    
    print(f"Datum teď: {datetime.now()}")
    print(f"Proběhly tři kvery a zabralo to {time.time()-start} vteřin")
    start = time.time()
    
    print(f"Graph24: {graphCount24}, graph: {graphCount}, graph Battery: {graphBatteryCount}")
    # Pokud nenalezne žádné záznamy, tak provede stejné příkazy, ale nyní hledá časový úsek od posledního záznamu hlásiče
    if graphCount24 == 0:
        maxdate = db.session.execute(query_max_time,{"orp":orp}).first()[0]
        print(f"Maxdate: {maxdate}")
        print(f"Maxdate: {maxdate.strftime('%Y-%m-%d %H:%M:%S')}")
        graph24 = db.session.execute(query_hladina,{"now":maxdate.strftime('%Y-%m-%d %H:%M:%S'),"inter":1,"orp":orp,"lim":10000})
        if graphCount == 0:
            graph = db.session.execute(query_hladina,{"now":maxdate.strftime('%Y-%m-%d %H:%M:%S'),"inter":30,"orp":orp,"lim":10000})
        
    
    print(f"Proběhla podmínka prázdnoty a zabralo to {time.time()-start} vteřin")
    start = time.time()

    dataGraf = {}
    dataGraf24 = {}
    dataGrafBattery = {}
    # Vytvoření slovníků podle předchozích dotazů, formát "čas":"hladina"
    for zaznam in graph24:
        # print(type(zaznam.hladina))
        if type(zaznam.hladina) == int or type(zaznam.hladina) == float:
            dataGraf24[zaznam.timeformat]=zaznam.hladina
    for zaznam in graph:
        if type(zaznam.hladina) == int or type(zaznam.hladina) == float:
            dataGraf[zaznam.timeformat]=zaznam.hladina
    for zaznam in graphbattery:
        if type(zaznam.battery) == str:
            dataGrafBattery[zaznam.timeformat]=zaznam.battery

    latest=datetime.strptime(max(dataGraf24), '%Y-%m-%dT%H:%M:%S')
    print((datetime.now() - latest).days)
    late = 0
    if (datetime.now() - latest).days > 1:
        late = 1

    print(f"Proběhlo uložení do slovníčků a zabralo to {time.time()-start} vteřin")
    start = time.time()
    
    
    # Nalezne minimální a maximální hodnoty baterky za poslední tři měsíce
    if graphBatteryCount != 0:
        batteryMin = min(dataGrafBattery, key=dataGrafBattery.get)
        batteryMax = max(dataGrafBattery, key=dataGrafBattery.get)
    else: # Pokud není žádný záznam baterky za poslední tři měsíce, tak nastavit na nuly, aby stránka nehlásila errory
        batteryMax = 0
        batteryMin = 0
        dataGrafBattery[0]=0 # V Jinja šabloně se hledá ve slovníku podle klíče (který bude 0)

    
    print(f"Proběhlo vybrání hlásiče a zabralo to {time.time()-start} vteřin")

    # Vygeneruje stránku podle přiloženého templatua pošle ji další argumenty
    return render_template(
        'eviListHlasice.html',
        curpage="profily", # Označení nynější stránky pro zvýraznění v navbaru
        dataGraf=dataGraf, # Slovník dat pro měsíční graf
        dataGraf24=dataGraf24, # Slovník dat pro 24 hodinový graf
        dataGrafBattery=dataGrafBattery, # Slovník dat pro záznamy z baterie za poslední tři měsíce
        latest=latest, # Poslední naměřený údaj
        late=late, # Příznak jeslti máme neaktuální data
        batteryMin=batteryMin,
        batteryMax=batteryMax,
        hlasic=hlasic, 
        title="Portabo Voda Hlásič",
        description="Evidenční list profilu hlásiče"
    )

# Funkce pro zobrazení stránky O projektu
@main_bp.route('/oprojektu', methods=['GET'])
def oprojektu():

    # Vygeneruje stránku podle přiloženého templatu a pošle ji další argumenty
    return render_template(
        'oprojektu.html',
        curpage="oprojektu", # Označení nynější stránky pro zvýraznění v navbaru
        title="Portabo Voda O Projektu",
        description="Popis projektu Portabo Voda"
    )

# Funkce pro poslání souboru uživateli
@main_bp.route('/download/<path:filename>', methods=['GET','POST'])
def download(filename):

    # Spojení cesty k aplikaci s názvem upload složky podle configu
    uploads = os.path.join(current_app.root_path, current_app.config['UPLOAD_FOLDER'])

    # Zaslání souboru(filename) z upload složky uživateli. as_attachment způsobí, že soubor nezobrazí, ale rovnou dá na stažení
    return send_from_directory(directory=uploads, path=filename,as_attachment=True)

# Funkce pro zobrazení stránky Odkazy
@main_bp.route('/odkazy', methods=['GET'])
def odkazy():

    # Vygeneruje stránku podle přiloženého templatua pošle ji další argumenty
    return render_template(
        'odkazy.html',
        curpage="odkazy", # Označení nynější stránky pro zvýraznění v navbaru
        title="Portabo Voda Odkazy",
        description="Vhodné odkazy spojené s Portabo Vodou"
    )

# Funkce pro zobrazení stránky Novinky
@main_bp.route('/novinky', methods=['GET'])
def novinky():

    # Vygeneruje stránku podle přiloženého templatua pošle ji další argumenty
    return render_template(
        'novinky.html',
        curpage="novinky", # Označení nynější stránky pro zvýraznění v navbaru
        title="Portabo Voda Novinky",
        description="Nové zprávy v projektu Portabo Voda"
    )

voda-py/app/app/templates/api.html
{% extends "base.html" %}

{% block content %}
    {% set count=0 %}
    <h1>API Portabo Voda</h1>
    <p>Na níže uvedeném odkaze najdete GraphQL API, které poskytuje přístup ke všem aktuálním hlásným profilům pomocí jednoduchého jazyka a vrací data ve formátu JSON.</p>
    <p>Odkaz lze využít jak pro zkoumání dat pomocí příslušného nástroje, tak pro automatické stahování dat. Po rozkliknutí odkazu naleznete po pravé straně záložku DOCS, ve které jsou vidět dostupné funkce. Níže také vidíte ukázku použití obou funkcí. První příkaz vypíše zeměpisné šířku a délku, ORP, aktuální hladinu a textový popis hladiny dle povodňového plánu všech hlásných profilů. Druhý příkaz je velmi podobný, ale slouží pro vypsání pouze jednoho hlásného profilu identifikovaného dle jednoznačného identifikátoru ORP (zde BI-03). Je důležité nezapomenout složené závorky kolem celého příkazu (začínají na druhém řádku).</p>
    
    <center><a href="{{url_for('api_bp.graphql_server')}}">Odkaz na API</a></center>
    <div class="row" style="margin:20px;">
        <div class="col-md" style="margin:20px;">
            <center>
            <img src="{{url_for('static',filename='Img/listHlasice.png')}}"></center>
        </div>
        <div class="col-md" style="margin:20px;">
            <center>
            <img src="{{url_for('static',filename='Img/getHlasic.png')}}"></center>
        </div>
    </div>
    

    </div>
{% endblock %}

voda-py/app/app/templates/home.html
{% extends "base.html" %}

{% block scripts %}
<script type='text/javascript' src="{{url_for('static',filename='Dist/js/CZ042-single.js')}}"></script>
{% endblock %}

{% block content %}
    <div id="mapid" style="width: 100%; height: 100%; display: block"></div>

    <script type="text/javascript">
    var map = L.map('mapid').setView([50.492, 13.9], 9);
    map._layersMaxZoom = 19;
    let marker;
    var markers = new L.markerClusterGroup();
    var markerClusters = L.markerClusterGroup();
    var vse = new L.markerClusterGroup();map.addLayer(vse);
    var such = new L.markerClusterGroup();map.addLayer(such);
    var norm = new L.markerClusterGroup();map.addLayer(norm);
    var nelz = new L.markerClusterGroup();map.addLayer(nelz); 
    var vypn = new L.markerClusterGroup();map.addLayer(vypn);
    var spa1 = new L.markerClusterGroup();map.addLayer(spa1);
    var spa2 = new L.markerClusterGroup();map.addLayer(spa2);
    var spa3 = new L.markerClusterGroup();map.addLayer(spa3);


    var Stadia_Outdoors = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 20,
        layers: [ markers,such,norm,spa1,spa2,spa3],
        attribution: '&copy; <a href="https://stadiamaps.com/">Stadia Maps</a>, &copy; <a href="https://openmaptiles.org/">OpenMapTiles</a> &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors'
        }).addTo(map);
        // pridani ikonek ruzneho tvaru nebo barev
        LeafIcon = L.Icon.extend({
            options: {
                iconSize:     [36, 36],
            }
        });

    var	SPA1Icon = new LeafIcon({iconUrl: "{{ url_for('static', filename='Img/leafletIcons/SPA1.png')}}"}),
        SPA2Icon = new LeafIcon({iconUrl: "{{ url_for('static', filename='Img/leafletIcons/SPA2.png')}}"}),
        SPA3Icon = new LeafIcon({iconUrl: "{{ url_for('static', filename='Img/leafletIcons/SPA3.png')}}"}),
        SUCHIcon = new LeafIcon({iconUrl: "{{ url_for('static', filename='Img/leafletIcons/SUCHO.png')}}"}),
        NELZIcon = new LeafIcon({iconUrl: "{{ url_for('static', filename='Img/leafletIcons/NELZE.png')}}"}),
        VYPNIcon = new LeafIcon({iconUrl: "{{ url_for('static', filename='Img/leafletIcons/VYPNUTO.png')}}"}),
        NORMIcon = new LeafIcon({iconUrl: "{{ url_for('static', filename='Img/leafletIcons/NORMAL.png')}}"});

    var popup = L.popup();

        function onMapClick(e) {
            popup
                .setLatLng(e.latlng)
                .setContent("Pozice na mapě " + e.latlng.toString())
                .openOn(map);
        }

        map.on('click', onMapClick);
    //CZ042geoData  definovano v CZ042.js kde jsou ulozeny geodata ohledne uzemi Usteckeho Kraje NUTS CZ042
    L.geoJson(Kadan_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Litomerice_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Lovosice_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Roudnice_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Louny_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Podborany_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Zatec_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Litvinov_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Most_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Bilina_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Teplice_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Usti_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Decin_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Rumburk_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Varnsdorf_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    L.geoJson(Chomutov_geojson,{style:{color: "#867979", opacity:0.9}}).addTo(map);
    
    </script>
    <script type="text/javascript">

    var count = 0
    var poctyNORM = 0
    var poctySPA1 = 0
    var poctySPA2 = 0
    var poctySPA3 = 0
    var poctyVYPN = 0
    var poctyNELZ = 0
    {% for hlasic in hlasice %}

        {% if(hlasic.topic[0:4]=='/udp') %}
            var typ="UDP senzor {{hlasic.topic}}";
        {% else %}
            var typ="WWW parsing - http://voda.kr-ustecky.cz {{hlasic.topic}}";
        {% endif %}

        // ořezávání dat
        {% if hlasic.nulovy_stav %}
            {% set topLevel = hlasic.FloodStageLevel4|round|int + ((hlasic.nulovy_stav - hlasic.FloodStageLevel4|round|int)*7/10) %}
        {% else %}
            {% set topLevel = hlasic.FloodStageLevel4|round|int + 40 %}
        {% endif %}

        //var popupopen=".on('popupopen', function (popup) { ukazDetail(\"{{hlasic.ORP}}\");})";
        var popisek=" <br>{{hlasic.Adresa}} <br> zdroj dat =";
        popisek +=typ;
        popisek +=" <br> hladina "
        {% if hlasic.distance is not none and hlasic.hladina > -50 and hlasic.hladina < topLevel %}
        popisek +="= {{hlasic.hladina|round|int}} [cm]"
        {% else %}
        popisek +="nelze zjistit" // nelze zjistit
        {% endif %}        
        popisek +="<br> <a href={{url_for('main_bp.hlasic',orp=hlasic.ORP)}}>";
        popisek +="Přehled pro stanici {{hlasic.ORP}}</a>"; // onmouseover=ukazDetail('{{hlasic.ORP}}')
        

        var urovenFiltr = "{{hlasic.uroven[0:4]|upper}}"
 
        // odstranět dodatek funkce, která je nefunkční -> .on('popupopen', function (popup) { ukazDetail("{{hlasic.ORP}}");})
        if (urovenFiltr == "NORM" || urovenFiltr == "SUCH") {
            poctyNORM+=1;
            L.marker([{{hlasic.lat}},{{hlasic.lon}}], {icon: NORMIcon}).bindPopup("{{hlasic.ORP}} " + count + " " + urovenFiltr + popisek).addTo(norm);
            L.marker([{{hlasic.lat}},{{hlasic.lon}}], {icon: NORMIcon}).bindPopup("{{hlasic.ORP}} " + count + " " + urovenFiltr + popisek).addTo(vse);
        } else if (urovenFiltr == "SPA1") {
            poctySPA1+=1
            L.marker([{{hlasic.lat}},{{hlasic.lon}}], {icon: SPA1Icon}).bindPopup("{{hlasic.ORP}}" + count + urovenFiltr + popisek ).addTo(spa1);
            L.marker([{{hlasic.lat}},{{hlasic.lon}}], {icon: SPA1Icon}).bindPopup("{{hlasic.ORP}}" + count + urovenFiltr + popisek ).addTo(vse);
        } else if (urovenFiltr == "SPA2") { 
            poctySPA2+=1; 
            L.marker([{{hlasic.lat}},{{hlasic.lon}}], {icon: SPA2Icon}).bindPopup("{{hlasic.ORP}}" + count + urovenFiltr + popisek ).addTo(spa2);
            L.marker([{{hlasic.lat}},{{hlasic.lon}}], {icon: SPA2Icon}).bindPopup("{{hlasic.ORP}}" + count + urovenFiltr + popisek ).addTo(vse);
        } else if (urovenFiltr == "SPA3") {
            poctySPA3+=1;
            L.marker([{{hlasic.lat}},{{hlasic.lon}}], {icon: SPA3Icon}).bindPopup("{{hlasic.ORP}}" + count + urovenFiltr + popisek ).addTo(spa3);
            L.marker([{{hlasic.lat}},{{hlasic.lon}}], {icon: SPA3Icon}).bindPopup("{{hlasic.ORP}}" + count + urovenFiltr + popisek ).addTo(vse);
        } else if (urovenFiltr == "NELZ") {
            poctyNELZ+=1;
            L.marker([{{hlasic.lat}},{{hlasic.lon}}], {icon: NELZIcon}).bindPopup("{{hlasic.ORP}}" + count + urovenFiltr + popisek ).addTo(nelz);
            L.marker([{{hlasic.lat}},{{hlasic.lon}}], {icon: NELZIcon}).bindPopup("{{hlasic.ORP}}" + count + urovenFiltr + popisek ).addTo(vse);
        } else if (urovenFiltr == "VYPN") {
            poctyVYPN+=1;
            L.marker([{{hlasic.lat}},{{hlasic.lon}}], {icon: VYPNIcon}).bindPopup("{{hlasic.ORP}}" + count + urovenFiltr + popisek ).addTo(vypn);
            L.marker([{{hlasic.lat}},{{hlasic.lon}}], {icon: VYPNIcon}).bindPopup("{{hlasic.ORP}}" + count + urovenFiltr + popisek ).addTo(vse);
        }
        count += 1;
        

    {% endfor %}

    </script>
    <script type="text/javascript">
    var poctyVSE = poctyNORM + poctySPA1 + poctySPA2 + poctySPA3 + poctyNELZ + poctyVYPN;
    var VSEo = " " + poctyVSE + "-Vše dohromady";
    var NORMo = " <img src={{ url_for('static', filename='Img/leafletIcons/NORMAL.png')}} height=24> " + poctyNORM + "- Normalni stav";
    var SPA1o = " <img src={{ url_for('static', filename='Img/leafletIcons/SPA1.png')}} height=24> " + poctySPA1 + "- SPA1 "
    var SPA2o = " <img src={{ url_for('static', filename='Img/leafletIcons/SPA2.png')}} height=24> " + poctySPA2 + "- SPA2 "
    var SPA3o = " <img src={{ url_for('static', filename='Img/leafletIcons/SPA3.png')}} height=24> " + poctySPA3 + "- SPA3 "
    var NELZo = " <img src={{ url_for('static', filename='Img/leafletIcons/NELZE.png')}} height=24> " + poctyNELZ + " - Nelze určit "
    var VYPNo = " <img src={{ url_for('static', filename='Img/leafletIcons/VYPNUTO.png')}} height=24>  " + poctyVYPN + "- Vypnuto "
    var overlays = {
        [NELZo]: nelz, 
        [NORMo]: norm,
        [SPA1o]: spa1,
        [SPA2o]: spa2,
        [SPA3o]: spa3,
        [VYPNo]: vypn, 
        [VSEo]: vse };
    L.control.layers(overlays,null,{collapsed:false,position: 'topleft',autoZIndex:true}).addTo(map);        
    </script>

{% endblock %}

voda-py/app/app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('main_bp.home')}}">Povodňový systém Ústeckého kraje</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse ms-auto" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a {% if curpage == "home" %} class="nav-link active" aria-current="page" {% else %} class="nav-link" {% endif %} href="{{url_for('main_bp.home')}}">Domů</a>
          </li>
          <li class="nav-item">
            <a {% if curpage == "profily" %} class="nav-link active" aria-current="page" {% else %} class="nav-link" {% endif %} href="{{url_for('main_bp.hlasice')}}">Profily</a>
          </li>
          <li class="nav-item">
            <a {% if curpage == "novinky" %} class="nav-link active" aria-current="page" {% else %} class="nav-link" {% endif %} href="{{url_for('main_bp.novinky')}}">Novinky</a>
          </li>
          <li class="nav-item">
            <a {% if curpage == "oprojektu" %} class="nav-link active" aria-current="page" {% else %} class="nav-link" {% endif %} href="{{url_for('main_bp.oprojektu')}}">O projektu</a>
          </li>
          <li class="nav-item">
            <a {% if curpage == "odkazy" %} class="nav-link active" aria-current="page" {% else %} class="nav-link" {% endif %} href="{{url_for('main_bp.odkazy')}}">Odkazy</a>
          </li>
          <li class="nav-item">
            <a {% if curpage == "api" %} class="nav-link active" aria-current="page" {% else %} class="nav-link" {% endif %} href="{{url_for('api_bp.api')}}">API</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="mailto:kejzlar.t@kr-ustecky.cz">Mailme</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

voda-py/app/app/templates/novinky.html
{% extends "base.html" %}

{% block content %}
    <h1>Novinky</h1>

    <br><br><strong><p>26. 5. 2021</p></strong>
    <p>Osadili jsme další čidla. Nově monitorujeme hladiny toků v <a href={{url_for('main_bp.hlasic',orp="DE-01")}}>Huntířově</a>, <a href={{url_for('main_bp.hlasic',orp="UL-06")}}>Lhotě pod Pannou</a> a <a href={{url_for('main_bp.hlasic',orp="UL-13")}}>Proboštově</a>.</p>
    <br><br><strong><p>18. 5. 2021</p></strong>
    <p>Pokud jste obcí či městem v Ústeckém kraji a také byste chtěli, abychom vám hlídali hladinu toku, neváhejte nás kontaktovat na <a href="mailto:kejzlar.t@kr-ustecky.cz">kejzlar.t@kr-ustecky.cz</a>.</p>
    <br><br><strong><p>22. 2. 2021</p></strong>
    <p>Podmínky zapojení se jsou popsány ve smlouvě o spolupráci, kterou si můžete stáhnout níže.</p>
{% endblock %}

voda-py/app/app/templates/odkazy.html
{% extends "base.html" %}

{% block content %}
    <h1>Odkazy</h1>

    <br><a href="www.chmu.cz">ČHMÚ</a>
    <br><a href="www.povis.cz">Povis</a>
    <br><a href="https://webmap.dppcr.cz/dpp_cr/editor.dll?GEN=LST&map=info_pp_data&TS=orp_pp&CF_SQY=C%5BCZNUTS3%5DECZ042">Povodňové plány na území Ústeckého kraje</a>
    <br><a href="www.pla.cz">Povodí Labe</a>
    <br><a href="www.poh.cz">Povodí Ohře</a>
    <br><a href="www.kr-ustecky.cz">Ústecký kraj</a>

{% endblock %}

voda-py/app/app/templates/profilyHlasicu.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    {% set ns = namespace(show=1) %}
    <h1>Seznam všech hlásičů podle okresu</h1>
    <div class="row">
        <div class="col-lg">
            {% for key, value in hlasice.items() %}
            {% if key == delitel[0] %} {% set ns.show=0 %} {% endif %}
                {% if ns.show and value|length > 0 %}
                <h2>{{key}}</h2>
                    {% for hlasic in value %}
                    <a href="{{ url_for('main_bp.hlasic', orp=hlasic.ORP) }}">{{hlasic.ORP}} {{hlasic.Obec}}</a><br>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </div>
        <div class="col-lg">
            {% for key, value in hlasice.items() %}
            {% if key == delitel[0] %} {% set ns.show=1 %} {% endif %}
            {% if ns.show and value|length > 0 %}
                <h2>{{key}}</h2>
                    {% for hlasic in value %}
                    <a href="{{ url_for('main_bp.hlasic', orp=hlasic.ORP) }}">{{hlasic.ORP}} {{hlasic.Obec}}</a><br>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </div>
    
    </div>
</div>
{% endblock %}